const stockProductos2 = [
    {   id: 1,
        img: '../img/remera1.jpg',
        marca: 'REMERA NIKE CLUB',  
        precio: 6.099,
        cantidad: 1,
    }, 
    {  
        id: 2,
        img: '../img/sweater1.jpg',
        marca: 'SWEATER DE HOMBRE EN LANA DE MERINO',
        precio: 21.999,
        cantidad: 1,
    },
    {   
        id: 3,
        img: '../img/buzo1.jpg',
        marca: 'BUZO ADIDAS ORIGINALS CAMO',  
        precio: 24.199,
        cantidad: 1,
    },
    {   id: 4, 
        img: '../img/campera1.webp',
        marca: 'CAMPERA JORDAN JUMPMAN',
        precio: 25.299,
        cantidad: 1,
     },
    {   id: 5,
        img: '../img/pantalon1.jpg',
        marca: 'PANTALON ADIDAS ORIGINALS ADICOLOR',
        precio: 24.999,
        cantidad: 1,
     },
]