const stockProductos = [
    {   id: 1,
        img: '../img/remera1.jpg',
        marca: 'REMERA NIKE CLUB',  
        precio: 6.099,
        cantidad: 1,
    }, 
    {  
        id: 2,
        img: '../img/sweater1.jpg',
        marca: 'SWEATER DE HOMBRE EN LANA DE MERINO',
        precio: 21.999,
        cantidad: 1,
    },
    {   
        id: 3,
        img: '../img/buzo1.jpg',
        marca: 'BUZO ADIDAS ORIGINALS CAMO',  
        precio: 24.199,
        cantidad: 1,
    },
    {   id: 4, 
        img: '../img/campera1.webp',
        marca: 'CAMPERA JORDAN JUMPMAN',
        precio: 25.299,
        cantidad: 1,
     },
    {   id: 5,
        img: '../img/pantalon1.jpg',
        marca: 'PANTALON ADIDAS ORIGINALS ADICOLOR',
        precio: 24.999,
        cantidad: 1,
     },
    {   id: 6,
        img: '../img/remera2.jpg',
        marca: 'REMERA PUMA POWER',  
        precio: 8.999,
        cantidad: 1,
     }, 
     {   id: 7,
        img: '../img/sweater2.jpg',
        marca: 'SWEATER DE MUJER LACOSTE', 
        precio: 25.999,
        cantidad: 1,
     }, 
     {   id: 8,
        img: '../img/buzo2.jpg',
        marca: 'BUZO NIKE ICON CLASH',  
        precio: 17.099,
        cantidad: 1,
     }, 
     {   id: 9,
        img: '../img/campera2.jpg',
        marca: 'CAMPERA ADIDAS ORIGINALS WINTER',  
        precio: 34.099,
        cantidad: 1,
     },
     {   id: 10,
        img: '../img/pantalon2.jpg',
        marca: 'PANTALÓN DE MUJER LACOSTE',  
        precio: 17.999,
        cantidad: 1,
     },  
     
     {   id: 11,
        img: '../img/zapatilla1.jpg',
        marca: 'ZAPATILLAS PUMA FUTURE RIDER',  
        precio: 19.499,
        cantidad: 1,
     }, 
     {   id: 12,
        img: '../img/zapatilla2.jpg',
        marca: 'JORDAN 1 LOW BLACK GUAVA ICE',  
        precio: 117.975,
        cantidad: 1,
     }, 
     {   id: 13,
        img: '../img/zapatilla3.jpg',
        marca: 'ZAPATILLAS JORDAN SERIES ES',  
        precio: 26.399,
        cantidad: 1,
     },
     {   id: 14,
        img: '../img/zapatilla4.jpg',
        marca: 'BOTITAS JORDAN AIR 3 RETRO',  
        precio: 59.399,
        cantidad: 1,
     },
     {   id: 15,
        img: '../img/zapatilla5.jpg',
        marca: 'ZAPATILLAS NIKE AIR FORCE 1 07 ESS',  
        precio: 31.399,
        cantidad: 1,
     },
     {   id: 16,
        img: '../img/zapatilla6.jpg',
        marca: 'ZAPATILLAS ADIDAS ORIGINALS FORUM',  
        precio: 30.999,
        cantidad: 1,
     },
     {   id: 17,
        img: '../img/zapatilla7.jpg',
        marca: 'ZAPATILLAS DE MUJER L--1 LACOSTE',  
        precio: 34.999,
        cantidad: 1,
     },
     {   id: 18,
        img: '../img/zapatilla8.jpg',
        marca: 'ZAPATILLAS PUMA MAYZE',  
        precio: 21.999,
        cantidad: 1,
     },
     {   id: 19,
        img: '../img/zapatilla9.jpg',
        marca: 'ZAPATILLAS ADIDAS ORIGINALS NIZZA',  
        precio: 15.399,
        cantidad: 1,
     },
     {   id: 20,
        img: '../img/zapatilla10.jpg',
        marca: 'ZAPATILLAS DE MUJER ZIANE PLUS LACOSTE',  
        precio: 26.999,
        cantidad: 1,
     }, 
     {   id: 21,
        img: '../img/zapatilla11.jpg',
        marca: 'ZAPATILLAS DE HOMBRE L--1 LACOSTE',  
        precio: 34.999,
        cantidad: 1,
     }, 
     {   id: 22,
        img: '../img/zapatilla12.jpg',
        marca: 'ZAPATILLAS NIKE W BLAZER LOW 77',
        precio: 25.899,
        cantidad: 1,
     }, 
]