const stockProductos3 = [
    {   id: 6,
        img: '../img/remera2.jpg',
        marca: 'REMERA PUMA POWER',  
        precio: 8.999,
        cantidad: 1,
     }, 
     {   id: 7,
        img: '../img/sweater2.jpg',
        marca: 'SWEATER DE MUJER LACOSTE', 
        precio: 25.999,
        cantidad: 1,
     }, 
     {   id: 8,
        img: '../img/buzo2.jpg',
        marca: 'BUZO NIKE ICON CLASH',  
        precio: 17.099,
        cantidad: 1,
     }, 
     {   id: 9,
        img: '../img/campera2.jpg',
        marca: 'CAMPERA ADIDAS ORIGINALS WINTER',  
        precio: 34.099,
        cantidad: 1,
     },
     {   id: 10,
        img: '../img/pantalon2.jpg',
        marca: 'PANTALÓN DE MUJER LACOSTE',  
        precio: 17.999,
        cantidad: 1,
     },  
     
     {   id: 11,
        img: '../img/zapatilla1.jpg',
        marca: 'ZAPATILLAS PUMA FUTURE RIDER',  
        precio: 19.499,
        cantidad: 1,
     }, 
]